@startuml
SETUP: The loan is deployed, attributes can be set
FUNDING : The loan is being funded.
PAYING: The loan is accepted and the principal collected by the borrower\nThe loan is being paying back.
CANCELED: The loan is canceled.
FINISHED: The loan is completly repayed.
DEFAULTED: The loan wasn't repayed.

[*] --> SETUP 
SETUP --> FUNDING: being()
FUNDING --> FUNDING: fund()
FUNDING -left-> FUNDING: withdraw()
FUNDING --> PAYING: accept()
FUNDING --> CANCELED: cancel()
CANCELED -left-> CANCELED: withdraw()
CANCELED --> [*]
PAYING --> PAYING: payback()
PAYING -left-> PAYING: withdraw()
PAYING --> FINISHED: payback()
FINISHED -left-> FINISHED: withdraw()
PAYING --> DEFAULTED: default()
DEFAULTED -left-> DEFAULTED: withdraw()
DEFAULTED --> [*]
FINISHED -->  [*]
@enduml
